name: Halo Dunia Action             # Nama workflow (bebas)
on: [push]                          # Pemicu (trigger): jalan saat ada push ke repo

jobs:
  cetak-pesan:                      # Nama pekerjaan
    runs-on: ubuntu-latest          # Sistem operasi yang digunakan (virtual runner)
    steps:
      - name: Ambil kode (Checkout)
        uses: actions/checkout@v4   # Action resmi untuk menyalin kode ke runner

      - name: Jalankan Perintah
        run: echo "Halo! Workflow GitHub pertama saya berhasil jalan."
